"""Browser integration tests for the standalone HTML.
The managed Chromium blocks navigation, so set_content is used with an in-memory
Storage-compatible fixture. These tests do not establish real Claude execution
or persistence across actual file:// browser sessions.
"""
from pathlib import Path
from playwright.sync_api import sync_playwright
import json, traceback, os, shutil, sys
ROOT=Path(__file__).resolve().parents[1]
HTML=(ROOT/'index.html').read_text(encoding='utf-8')
OUT=Path(os.environ.get('SQUAD_PREVIEW_DIR',str(ROOT/'previews')))
OUT.mkdir(parents=True,exist_ok=True)
results=[]
STORAGE="""(initial) => { const data=new Map(Object.entries(initial||{})); Object.defineProperty(window,'localStorage',{value:{getItem:k=>data.has(String(k))?data.get(String(k)):null,setItem:(k,v)=>data.set(String(k),String(v)),removeItem:k=>data.delete(String(k)),clear:()=>data.clear()}}); }"""

def test(name, condition=True):
    assert condition, name
    results.append({'name':name,'passed':True})
    print('PASS',name,flush=True)

def snap(page): return page.evaluate('SquadCode.getSnapshot()')
def close(page):
    if page.locator('#modalRoot .modal').count(): page.locator('#modalRoot [data-action=modal-close]').first.click()
def click(page,action,root='#modalRoot'):
    page.locator(f'{root} [data-action="{action}"]').first.click()
def wait_not_running(page):page.wait_for_function('!runner',timeout=15000)

with sync_playwright() as pw:
 binary=os.environ.get('CHROMIUM_EXECUTABLE') or shutil.which('chromium')
 browser=pw.chromium.launch(executable_path=binary,headless=True)
 context=browser.new_context(viewport={'width':1600,'height':1000},device_scale_factor=1)
 page=context.new_page();errors=[];requests=[]
 page.on('pageerror',lambda e:errors.append(str(e)))
 page.on('request',lambda r:requests.append(r.url))
 page.evaluate(STORAGE,{})
 page.set_content(HTML,wait_until='load')
 page.wait_for_timeout(200)
 try:
    test('Boots with six agents, the approved setup and six sample features',len(snap(page)['agents'])==6 and len(snap(page)['projects'][0]['features'])==7 and snap(page)['projects'][0]['features'][0]['setup'])
    test('Six independently interactive map nodes',page.locator('.map-node').count()==6)
    test('Single example feature is visibly complete',snap(page)['projects'][0]['features'][0]['status']=='done')
    page.locator('#leftHud [data-id="agent-backend"]').click()
    test('Selecting a map agent updates the inspector',page.locator('.identity-name').inner_text()=='FORGE')
    click(page,'agent-edit','#rightHud')
    page.locator('#agentName').fill('FORGE API')
    page.locator('#agentDescription').fill('Backend, contracts and persistence.')
    page.locator('[data-tab=prompt]').click()
    page.locator('#agentPrompt').fill('You are the API engineer. Use functional TypeScript and validate all inputs.')
    page.locator('[data-tab=tools]').click()
    page.locator('[name=tools][value=Glob]').uncheck()
    page.locator('button[form=agentForm]').click()
    backend=next(a for a in snap(page)['agents'] if a['id']=='agent-backend')
    test('Agent edits persist across editor tabs',backend['name']=='FORGE API' and 'Glob' not in backend['tools'] and 'functional TypeScript' in backend['prompt'])
    click(page,'agent-duplicate','#rightHud')
    test('Duplicate gets a distinct ID and name',len(snap(page)['agents'])==7)
    page.locator('#agentName').fill('NOVA')
    page.locator('#agentRole').select_option('frontend')
    page.locator('#agentImage').set_input_files(str(ROOT/'assets/commander.jpg'))
    page.wait_for_function("ui.draft.agent.image.startsWith('data:image/jpeg;base64,')")
    page.locator('button[form=agentForm]').click()
    nova=next(a for a in snap(page)['agents'] if a['name']=='NOVA')
    test('Uploaded avatar is validated, resized and stored',nova['image'].startswith('data:image/jpeg;base64,') and nova['role']=='frontend')
    click(page,'agent-edit','#rightHud');click(page,'agent-delete');click(page,'confirm')
    test('Deletion removes agent and project association',len(snap(page)['agents'])==6 and nova['id'] not in snap(page)['projects'][0]['agentIds'])

    click(page,'projects','#leftHud');click(page,'project-new','#projectsView')
    page.locator('button[form=opNewForm]').click()
    test('Nova operação refuses an empty name',page.locator('#opNewName').count()==1 and len(snap(page)['projects'])==1)
    page.locator('#opNewName').fill('Mission Control')
    page.locator('button[form=opNewForm]').click()
    click(page,'op-new-existing')
    page.locator('button[form=opNewSquadForm]').click()
    state=snap(page);pid=state['projectId'];p=next(p for p in state['projects'] if p['id']==pid)
    test('Nova operação creates the project at once with name, squad, folder and one sprint',len(state['projects'])==2 and p['name']=='Mission Control' and p['commanderId']=='agent-commander' and p['folder'] and len(p['sprints'])==1 and p['briefing']=='')
    setup=p['features'][0]
    test('Sprint 01 of a new operation starts with the project setup',len(p['features'])==1 and setup['setup'] and setup['key']=='F00' and setup['sprintId']==p['sprints'][0]['id'])
    # Every other feature depends on the setup: approve it here so the flow below can run.
    page.evaluate("setupOf().status='done';save();render()")
    page.locator('#projectBriefing').fill('Build a local project management application with clear acceptance criteria, safe input validation and human approval.')
    page.locator('button[form=projectForm]').click()
    for title in ('Workspace overview','Agent directory'):
        click(page,'feature-new','#projectsView')
        page.locator('#featureTitle').fill(title)
        page.evaluate("document.querySelector('#featureCriteria').value='Visible, validated and approved by a human.'")
        page.locator('button[form=featureForm]').click()
    state=snap(page);p=next(p for p in state['projects'] if p['id']==pid)
    test('Project creation captures briefing, commander, squad and features',len(p['features'])==3 and p['briefing'].startswith('Build a local'))
    f1,f2=[f['id'] for f in p['features'] if not f['setup']]
    test('New features depend on the project setup',all(f['dependencies']==[setup['id']] for f in p['features'] if not f['setup']))
    page.keyboard.press('f');click(page,'feature-new')
    page.locator('#featureTitle').fill('Audit trail')
    page.locator('#featureScope').select_option('qa')
    page.locator('#featurePriority').select_option('P2')
    page.locator('#featureCriteria').fill('Record all operations and verify visible state changes.')
    page.locator(f'[name=dependencies][value="{f1}"]').check()
    page.locator('button[form=featureForm]').click()
    f3=next(f['id'] for p in snap(page)['projects'] if p['id']==pid for f in p['features'] if f['title']=='Audit trail')
    test('Feature creation stores scope, priority and dependencies',len(next(p for p in snap(page)['projects'] if p['id']==pid)['features'])==4)
    page.locator('#featureSearch').fill('Audit')
    test('Feature search filters the board',page.locator('.feature-card').count()==1)
    page.locator('#featureSearch').fill('')
    page.locator(f'.feature-card[data-id="{f1}"]').click()
    page.locator(f'[name=dependencies][value="{f3}"]').check()
    page.locator('button[form=featureForm]').click()
    test('Cyclic dependencies are rejected without changing data',page.locator('#featureForm').count()==1 and next(f for p in snap(page)['projects'] if p['id']==pid for f in p['features'] if f['id']==f1)['dependencies']==[setup['id']])
    close(page)

    # Detect incomplete role coverage, then restore the specialist through the UI.
    click(page,'briefing','#leftHud');click(page,'project-edit')
    page.locator('[name=agentIds][value=agent-qa]').uncheck();page.locator('button[form=projectForm]').click()
    click(page,'distribute','#rightHud')
    test('Commander reports missing specialists',page.locator('.plan-error').count()==3 and page.locator('[data-action=plan-apply]').is_disabled())
    close(page);click(page,'briefing','#leftHud');click(page,'project-edit')
    page.locator('[name=agentIds][value=agent-qa]').check();page.locator('button[form=projectForm]').click()

    page.locator('.mode-nav [data-view=handoffs]').click()
    test('Handoff view switches to purple routing',page.evaluate('ui.view')=='handoffs')
    click(page,'handoff-new','#rightHud')
    page.locator('#handoffFrom').select_option('agent-backend')
    page.locator('#handoffTo').select_option('agent-frontend')
    page.locator('#handoffFeature').select_option(f1)
    page.locator('#handoffContext').fill('API contracts and acceptance criteria must travel with this feature.')
    page.locator('button[form=handoffForm]').click()
    p=next(p for p in snap(page)['projects'] if p['id']==pid)
    test('Manual handoff records context and updates the pending route',len(p['handoffs'])==1 and next(f for f in p['features'] if f['id']==f1)['route']==['agent-backend','agent-frontend'])
    click(page,'settings','.system-meta');page.locator('#demoSpeed').select_option('600');close(page)
    click(page,'run','#rightHud');click(page,'run','#rightHud')
    test('Demo can be paused',page.evaluate('runner.paused') is True)
    before=page.evaluate('activeFeature().step');page.wait_for_timeout(750)
    test('Paused simulation does not advance',page.evaluate('activeFeature().step')==before)
    click(page,'run','#rightHud');wait_not_running(page)
    f=next(f for p in snap(page)['projects'] if p['id']==pid for f in p['features'] if f['id']==f1)
    test('Simulated handoff produces per-agent reports',len(f['outputs'])==2)
    test('Completed route requires human review, not auto-approval',f['status']=='review')
    page.keyboard.press('f');page.locator(f'.feature-card[data-id="{f1}"]').click();click(page,'feature-approve')
    test('Human approval marks only reviewed feature complete',next(f for p in snap(page)['projects'] if p['id']==pid for f in p['features'] if f['id']==f1)['status']=='done')
    close(page);click(page,'distribute','#rightHud');click(page,'plan-apply')
    p=next(p for p in snap(page)['projects'] if p['id']==pid)
    test('Commander generates specialist routes by feature scope',next(f for f in p['features'] if f['id']==f2)['route']==['agent-po','agent-architect','agent-backend','agent-frontend','agent-qa'] and next(f for f in p['features'] if f['id']==f3)['route']==['agent-qa'])
    test('Approved dependency unlocks downstream feature',next(f for f in p['features'] if f['id']==f3)['status']=='ready')
    click(page,'run','#rightHud');wait_not_running(page)
    p=next(p for p in snap(page)['projects'] if p['id']==pid)
    test('Sequential simulation processes the available queue',sum(f['status']=='review' for f in p['features'])==2)
    page.keyboard.press('f');page.locator(f'.feature-card[data-id="{f2}"]').click();click(page,'feature-rework')
    test('Review can request another iteration',next(f for p in snap(page)['projects'] if p['id']==pid for f in p['features'] if f['id']==f2)['status']=='ready')
    close(page);page.locator('#leftHud [data-id=agent-backend]').click();click(page,'spawn','#rightHud')
    page.locator('#spawnFeature').select_option(f2);page.locator('button[form=spawnForm]').click();wait_not_running(page)
    f=next(f for p in snap(page)['projects'] if p['id']==pid for f in p['features'] if f['id']==f2)
    test('Individual spawn uses only the selected agent and returns to review',f['route']==['agent-backend'] and f['status']=='review')
    page.keyboard.press('f')
    for fid in [f2,f3]:
        page.locator(f'.feature-card[data-id="{fid}"]').click();click(page,'feature-approve')
    test('Progress reaches 100 percent only after human approval',page.locator('#operationProgress .progress-caption strong').inner_text()=='100%')
    close(page)

    # Zoom, pan, repositioning and visualization controls.
    before=page.evaluate('MapNetwork.getCamera()')
    click(page,'zoom-in','.map-side-controls')
    test('Zoom controls change the map camera',page.evaluate('MapNetwork.getCamera().scale')>before['scale'])
    click(page,'map-reset','.map-side-controls')
    test('Home restores the camera scale',abs(page.evaluate('MapNetwork.getCamera().scale')-before['scale'])<0.001)
    page.mouse.move(700,820);page.mouse.down();page.mouse.move(770,850,steps=8);page.mouse.up()
    test('Canvas pan moves the camera',abs(page.evaluate('MapNetwork.getCamera().x')-before['x'])>50)
    click(page,'map-reset','.map-side-controls')
    pos=page.locator('.map-node[data-id=agent-architect]').bounding_box()
    old=next(a for a in snap(page)['agents'] if a['id']=='agent-architect')['hex']
    page.keyboard.down('Shift');page.mouse.move(pos['x']+24,pos['y']+24);page.mouse.down();page.mouse.move(pos['x']+150,pos['y']+90,steps=8);page.mouse.up();page.keyboard.up('Shift')
    new=next(a for a in snap(page)['agents'] if a['id']=='agent-architect')['hex']
    test('Shift-drag moves the agent to another hex',new!=old)
    close(page)
    page.keyboard.press('h');test('Focus mode hides interactive HUD regions',page.locator('#workspace').evaluate("e=>e.classList.contains('focus-mode')"))
    page.locator('#restoreHud').click()
    test('Focus mode can restore all panels',not page.locator('#leftHud').evaluate('e=>e.inert'))
    click(page,'handoff-history','#rightHud')
    test('Handoff history shows accumulated transfers',page.locator('.timeline-row').count()>=5)
    close(page);page.keyboard.press('l')
    click(page,'log-filter');test('Operation log is readable and filterable',page.locator('.log-grid').count()>0)
    close(page)

    # State output and re-hydration are checked with a storage fixture, not OS persistence.
    stored=page.evaluate("localStorage.getItem('squad-code.network.v2')")
    fresh=context.new_page();fresh.evaluate(STORAGE,{'squad-code.network.v2':stored});fresh.set_content(HTML);fresh.wait_for_timeout(150)
    test('Workspace serializes and rehydrates with the storage fixture',fresh.evaluate('SquadCode.getSnapshot().projects.length')==2 and fresh.evaluate('SquadCode.getSnapshot().projectId')==pid)
    test('Exported snapshot is isolated from internal state',page.evaluate("(()=>{const x=SquadCode.getSnapshot();x.agents.length=0;return SquadCode.getSnapshot().agents.length===6})()"))
    test('Invalid workspace versions are rejected',page.evaluate("(()=>{try{normalizeWorkspace({version:42,agents:[],projects:[]});return false}catch{return true}})()"))
    test('Unknown roles are rejected',page.evaluate("(()=>{const x=SquadCode.getSnapshot();x.agents[0].role='constructor';try{normalizeWorkspace(x);return false}catch{return true}})()"))
    test('Unsafe uploaded image URLs are removed on import',page.evaluate("(()=>{const x=SquadCode.getSnapshot();x.agents[0].image='javascript:alert(1)';return normalizeWorkspace(x).agents[0].image==='';})()"))
    test('No network requests are needed',not any(url.startswith(('http://','https://')) for url in requests))
    test('No uncaught browser errors',not errors)
    fresh.close()
    # Fresh desktop view for accurate screenshots.
    art=context.new_page();art.evaluate(STORAGE,{});art.set_content(HTML);art.wait_for_timeout(500)
    art.screenshot(path=str(OUT/'squad-code-network-preview.png'))
    art.locator('.mode-nav [data-view=handoffs]').click();art.wait_for_timeout(300)
    art.locator('#toastRoot').evaluate('e=>e.innerHTML=""')
    art.screenshot(path=str(OUT/'squad-code-network-handoffs.png'))
    click(art,'agent-edit','#rightHud');art.wait_for_timeout(300)
    art.screenshot(path=str(OUT/'squad-code-network-studio.png'))
    close(art);art.keyboard.press('f');art.wait_for_timeout(200)
    art.screenshot(path=str(OUT/'squad-code-network-features.png'))
    mobile=context.new_page();mobile.set_viewport_size({'width':390,'height':844});mobile.evaluate(STORAGE,{});mobile.set_content(HTML);mobile.wait_for_timeout(300)
    test('Mobile layout has no horizontal page overflow',mobile.evaluate('document.documentElement.scrollWidth<=innerWidth'))
    mobile.screenshot(path=str(OUT/'squad-code-network-mobile.png'))
    mobile.locator('#leftHud [data-id=agent-commander]').click()
    test('Mobile agent selection opens the controllable studio',mobile.locator('#agentForm').is_visible())
    mobile.screenshot(path=str(OUT/'squad-code-network-mobile-studio.png'))
    close(mobile);mobile.keyboard.press('f')
    test('Mobile feature board is accessible and horizontally scrollable',mobile.locator('#kanbanRoot').is_visible())
 except Exception as exc:
    page.screenshot(path=str(OUT/'squad-code-network-test-failure.png'))
    results.append({'name':'failure','passed':False,'error':str(exc)})
    traceback.print_exc()
 finally:
    (ROOT/'tests/ui-results.json').write_text(json.dumps({'tests':results,'passed':sum(r['passed'] for r in results),'failed':sum(not r['passed'] for r in results),'browser_errors':errors,'limitations':['Managed Chromium URL navigation blocked; set_content and a Storage-compatible in-memory fixture used.','No authenticated Claude Code runtime was tested.']},indent=2))
    print('TOTAL',len(results),'PASSED',sum(r['passed'] for r in results),'ERRORS',errors)
    browser.close()

if any(not item['passed'] for item in results):
    sys.exit(1)
