"""Embed the avatar gallery: every assets/*.png becomes a small JPEG data URL in src/avatars.js.

The source PNGs are large (≈1254px, ~2 MB); the gallery shows them at ~100px, so they are
downscaled to AVATAR_SIZE and re-encoded as JPEG to keep the standalone HTML small.
Requires Pillow (pip install pillow). Run directly or via build.py.
"""
from pathlib import Path
import base64
import io
import json
import re

ROOT = Path(__file__).resolve().parents[1]
AVATAR_SIZE = 320
QUALITY = 82
UUID_RE = re.compile(r'^[0-9a-f]{8}-[0-9a-f]{4}-', re.I)


def label_of(stem: str, index: int) -> str:
    """File name -> gallery label ("mother-protocol" -> "MOTHER PROTOCOL"); unnamed files get a number."""
    if UUID_RE.match(stem):
        return f'AVATAR {index:02d}'
    return re.sub(r'[-_]+', ' ', stem).strip().upper()


def build_avatars() -> int:
    from PIL import Image

    entries = []
    for index, path in enumerate(sorted((ROOT / 'assets').glob('*.png'), key=lambda p: p.stem.lower()), 1):
        image = Image.open(path).convert('RGB')
        side = min(image.size)
        left, top = (image.width - side) // 2, (image.height - side) // 2
        image = image.crop((left, top, left + side, top + side)).resize((AVATAR_SIZE, AVATAR_SIZE), Image.LANCZOS)
        buffer = io.BytesIO()
        image.save(buffer, 'JPEG', quality=QUALITY, optimize=True, progressive=True)
        key = 'avatar-' + re.sub(r'[^a-z0-9]+', '-', path.stem.lower()).strip('-')
        entries.append({'key': key, 'label': label_of(path.stem, index),
                        'src': 'data:image/jpeg;base64,' + base64.b64encode(buffer.getvalue()).decode()})

    body = ',\n'.join(f'  {json.dumps(e["key"])}: {json.dumps(e["src"])}' for e in entries)
    meta = json.dumps([{'key': e['key'], 'label': e['label']} for e in entries], ensure_ascii=False)
    js = ('/* Generated by scripts/build-avatars.py from assets/*.png. Do not edit by hand. */\n'
          f'Object.assign(PORTRAITS, {{\n{body}\n}});\n'
          f'const AVATARS = {meta};\n')
    (ROOT / 'src/avatars.js').write_text(js, encoding='utf-8')
    print(f'Embedded {len(entries)} avatars ({len(js.encode("utf-8")) // 1024} KB)')
    return len(entries)


if __name__ == '__main__':
    build_avatars()
